Create function if no exist using default lambda config

diff --git a/.github/workflows/deploy.code.yml b/.github/workflows/deploy.code.yml
--- a/.github/workflows/deploy.code.yml
+++ b/.github/workflows/deploy.code.yml
@@ -12,16 +12,41 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v2
-      - uses: actions/setup-node@v2
-        with:
-          node-version: '14'
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v1
         with:
           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
           aws-region: us-east-1
+          mask-aws-account-id: 'no'
       - name: Deploy to AWS
+        id: deploy-to-aws
         run: |
           zip -j deploy.zip index.js
-          aws lambda update-function-code --function-name `echo $(jq -r '.FunctionName' lambda.config.json)` --zip-file=fileb://deploy.zip
+          aws lambda update-function-code --function-name `echo $(jq -r '.FunctionName' lambda.config.json)` --zip-file=fileb://deploy.zip 2> deploy.err || true
+          echo "::set-output name=error::$(grep -ohw 'deploy.err' -e 'Function not found')"
+    outputs:
+      aws-err: ${{steps.deploy-to-aws.outputs.error}}
+  create_lambda:
+    runs-on: ubuntu-latest
+    needs: deploy_lambda
+    if: ${{always() && needs.deploy_lambda.outputs.aws-err == 'Function not found'}}
+    steps:
+      - uses: actions/checkout@v2
+      - name: Configure AWS Credentials
+        uses: aws-actions/configure-aws-credentials@v1
+        with:
+          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          aws-region: us-east-1
+          mask-aws-account-id: 'no'
+      - name: Get aws error from deploy job
+        env:
+          DEPLOY_OUTPUT: ${{needs.deploy_lambda.outputs.aws-err}}
+        run: |
+          echo "$DEPLOY_OUTPUT"
+      - name: Create lambda function
+        run: |
+          echo "Create function"
+          zip -j deploy.zip index.js
+          aws lambda create-function --cli-input-json file://lambda.config.json --zip-file=fileb://deploy.zip
